services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8080
networks:
  app-network:
    driver: bridge