name: Gradle CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Temurin distribution is commonly used for OpenJDK
          java-version: '22'

      # Cache Gradle dependencies to speed up the build
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Give execute permission to Gradle wrapper script
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build and run tests using Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # Run tests
      - name: Run tests
        run: ./gradlew test